"""Added transaction and tag tables

Revision ID: 4bc985f005df
Revises:
Create Date: 2024-06-18 19:18:30.367369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bc985f005df"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description_from_bank", sa.String(), nullable=False),
        sa.Column("reference_id", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("value_date", sa.String(), nullable=False),
        sa.Column("withdraw_amount", sa.Float(), nullable=False),
        sa.Column("deposit_amount", sa.Float(), nullable=False),
        sa.Column("closing_balance", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "transaction_tag",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["bank_transaction.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("transaction_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_tag")
    op.drop_table("tag")
    op.drop_table("bank_transaction")
    # ### end Alembic commands ###
